package com.raishin.cardbatch.domain;

public class Datas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.id
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.ot
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer ot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.alias
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.setcode
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer setcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.type
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.atk
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer atk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.def
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer def;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.level
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.race
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer race;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.attribute
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer attribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.category
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.name
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.description
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datas.sum
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer sum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.id
     *
     * @return the value of datas.id
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.id
     *
     * @param id the value for datas.id
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.ot
     *
     * @return the value of datas.ot
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer getOt() {
        return ot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.ot
     *
     * @param ot the value for datas.ot
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public void setOt(Integer ot) {
        this.ot = ot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.alias
     *
     * @return the value of datas.alias
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.alias
     *
     * @param alias the value for datas.alias
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public void setAlias(Integer alias) {
        this.alias = alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.setcode
     *
     * @return the value of datas.setcode
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer getSetcode() {
        return setcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.setcode
     *
     * @param setcode the value for datas.setcode
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public void setSetcode(Integer setcode) {
        this.setcode = setcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.type
     *
     * @return the value of datas.type
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.type
     *
     * @param type the value for datas.type
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.atk
     *
     * @return the value of datas.atk
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer getAtk() {
        return atk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.atk
     *
     * @param atk the value for datas.atk
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public void setAtk(Integer atk) {
        this.atk = atk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.def
     *
     * @return the value of datas.def
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer getDef() {
        return def;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.def
     *
     * @param def the value for datas.def
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public void setDef(Integer def) {
        this.def = def;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.level
     *
     * @return the value of datas.level
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.level
     *
     * @param level the value for datas.level
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.race
     *
     * @return the value of datas.race
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer getRace() {
        return race;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.race
     *
     * @param race the value for datas.race
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public void setRace(Integer race) {
        this.race = race;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.attribute
     *
     * @return the value of datas.attribute
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.attribute
     *
     * @param attribute the value for datas.attribute
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public void setAttribute(Integer attribute) {
        this.attribute = attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.category
     *
     * @return the value of datas.category
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.category
     *
     * @param category the value for datas.category
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.name
     *
     * @return the value of datas.name
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.name
     *
     * @param name the value for datas.name
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.description
     *
     * @return the value of datas.description
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.description
     *
     * @param description the value for datas.description
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column datas.sum
     *
     * @return the value of datas.sum
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public Integer getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column datas.sum
     *
     * @param sum the value for datas.sum
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public void setSum(Integer sum) {
        this.sum = sum;
    }
}