package com.raishin.cardbatch.mapper;

import com.raishin.cardbatch.domain.Datas;
import com.raishin.cardbatch.domain.DatasExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface DatasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    @SelectProvider(type=DatasSqlProvider.class, method="countByExample")
    long countByExample(DatasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    @DeleteProvider(type=DatasSqlProvider.class, method="deleteByExample")
    int deleteByExample(DatasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    @Delete({
        "delete from datas",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    @Insert({
        "insert into datas (id, ot, ",
        "alias, setcode, ",
        "type, atk, def, ",
        "level, race, attribute, ",
        "category, name, ",
        "description, sum)",
        "values (#{id,jdbcType=INTEGER}, #{ot,jdbcType=INTEGER}, ",
        "#{alias,jdbcType=INTEGER}, #{setcode,jdbcType=INTEGER}, ",
        "#{type,jdbcType=INTEGER}, #{atk,jdbcType=INTEGER}, #{def,jdbcType=INTEGER}, ",
        "#{level,jdbcType=INTEGER}, #{race,jdbcType=INTEGER}, #{attribute,jdbcType=INTEGER}, ",
        "#{category,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{sum,jdbcType=INTEGER})"
    })
    int insert(Datas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    @InsertProvider(type=DatasSqlProvider.class, method="insertSelective")
    int insertSelective(Datas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    @SelectProvider(type=DatasSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ot", property="ot", jdbcType=JdbcType.INTEGER),
        @Result(column="alias", property="alias", jdbcType=JdbcType.INTEGER),
        @Result(column="setcode", property="setcode", jdbcType=JdbcType.INTEGER),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="atk", property="atk", jdbcType=JdbcType.INTEGER),
        @Result(column="def", property="def", jdbcType=JdbcType.INTEGER),
        @Result(column="level", property="level", jdbcType=JdbcType.INTEGER),
        @Result(column="race", property="race", jdbcType=JdbcType.INTEGER),
        @Result(column="attribute", property="attribute", jdbcType=JdbcType.INTEGER),
        @Result(column="category", property="category", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="sum", property="sum", jdbcType=JdbcType.INTEGER)
    })
    List<Datas> selectByExample(DatasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    @Select({
        "select",
        "id, ot, alias, setcode, type, atk, def, level, race, attribute, category, name, ",
        "description, sum",
        "from datas",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ot", property="ot", jdbcType=JdbcType.INTEGER),
        @Result(column="alias", property="alias", jdbcType=JdbcType.INTEGER),
        @Result(column="setcode", property="setcode", jdbcType=JdbcType.INTEGER),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="atk", property="atk", jdbcType=JdbcType.INTEGER),
        @Result(column="def", property="def", jdbcType=JdbcType.INTEGER),
        @Result(column="level", property="level", jdbcType=JdbcType.INTEGER),
        @Result(column="race", property="race", jdbcType=JdbcType.INTEGER),
        @Result(column="attribute", property="attribute", jdbcType=JdbcType.INTEGER),
        @Result(column="category", property="category", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="sum", property="sum", jdbcType=JdbcType.INTEGER)
    })
    Datas selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    @UpdateProvider(type=DatasSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Datas record, @Param("example") DatasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    @UpdateProvider(type=DatasSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Datas record, @Param("example") DatasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    @UpdateProvider(type=DatasSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Datas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    @Update({
        "update datas",
        "set ot = #{ot,jdbcType=INTEGER},",
          "alias = #{alias,jdbcType=INTEGER},",
          "setcode = #{setcode,jdbcType=INTEGER},",
          "type = #{type,jdbcType=INTEGER},",
          "atk = #{atk,jdbcType=INTEGER},",
          "def = #{def,jdbcType=INTEGER},",
          "level = #{level,jdbcType=INTEGER},",
          "race = #{race,jdbcType=INTEGER},",
          "attribute = #{attribute,jdbcType=INTEGER},",
          "category = #{category,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "sum = #{sum,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Datas record);
}