package com.raishin.cardbatch.mapper;

import com.raishin.cardbatch.domain.Datas;
import com.raishin.cardbatch.domain.DatasExample.Criteria;
import com.raishin.cardbatch.domain.DatasExample.Criterion;
import com.raishin.cardbatch.domain.DatasExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class DatasSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public String countByExample(DatasExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("datas");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public String deleteByExample(DatasExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("datas");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public String insertSelective(Datas record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("datas");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getOt() != null) {
            sql.VALUES("ot", "#{ot,jdbcType=INTEGER}");
        }
        
        if (record.getAlias() != null) {
            sql.VALUES("alias", "#{alias,jdbcType=INTEGER}");
        }
        
        if (record.getSetcode() != null) {
            sql.VALUES("setcode", "#{setcode,jdbcType=INTEGER}");
        }
        
        if (record.getType() != null) {
            sql.VALUES("type", "#{type,jdbcType=INTEGER}");
        }
        
        if (record.getAtk() != null) {
            sql.VALUES("atk", "#{atk,jdbcType=INTEGER}");
        }
        
        if (record.getDef() != null) {
            sql.VALUES("def", "#{def,jdbcType=INTEGER}");
        }
        
        if (record.getLevel() != null) {
            sql.VALUES("level", "#{level,jdbcType=INTEGER}");
        }
        
        if (record.getRace() != null) {
            sql.VALUES("race", "#{race,jdbcType=INTEGER}");
        }
        
        if (record.getAttribute() != null) {
            sql.VALUES("attribute", "#{attribute,jdbcType=INTEGER}");
        }
        
        if (record.getCategory() != null) {
            sql.VALUES("category", "#{category,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.VALUES("description", "#{description,jdbcType=VARCHAR}");
        }
        
        if (record.getSum() != null) {
            sql.VALUES("sum", "#{sum,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public String selectByExample(DatasExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("ot");
        sql.SELECT("alias");
        sql.SELECT("setcode");
        sql.SELECT("type");
        sql.SELECT("atk");
        sql.SELECT("def");
        sql.SELECT("level");
        sql.SELECT("race");
        sql.SELECT("attribute");
        sql.SELECT("category");
        sql.SELECT("name");
        sql.SELECT("description");
        sql.SELECT("sum");
        sql.FROM("datas");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Datas record = (Datas) parameter.get("record");
        DatasExample example = (DatasExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("datas");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getOt() != null) {
            sql.SET("ot = #{record.ot,jdbcType=INTEGER}");
        }
        
        if (record.getAlias() != null) {
            sql.SET("alias = #{record.alias,jdbcType=INTEGER}");
        }
        
        if (record.getSetcode() != null) {
            sql.SET("setcode = #{record.setcode,jdbcType=INTEGER}");
        }
        
        if (record.getType() != null) {
            sql.SET("type = #{record.type,jdbcType=INTEGER}");
        }
        
        if (record.getAtk() != null) {
            sql.SET("atk = #{record.atk,jdbcType=INTEGER}");
        }
        
        if (record.getDef() != null) {
            sql.SET("def = #{record.def,jdbcType=INTEGER}");
        }
        
        if (record.getLevel() != null) {
            sql.SET("level = #{record.level,jdbcType=INTEGER}");
        }
        
        if (record.getRace() != null) {
            sql.SET("race = #{record.race,jdbcType=INTEGER}");
        }
        
        if (record.getAttribute() != null) {
            sql.SET("attribute = #{record.attribute,jdbcType=INTEGER}");
        }
        
        if (record.getCategory() != null) {
            sql.SET("category = #{record.category,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("description = #{record.description,jdbcType=VARCHAR}");
        }
        
        if (record.getSum() != null) {
            sql.SET("sum = #{record.sum,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("datas");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("ot = #{record.ot,jdbcType=INTEGER}");
        sql.SET("alias = #{record.alias,jdbcType=INTEGER}");
        sql.SET("setcode = #{record.setcode,jdbcType=INTEGER}");
        sql.SET("type = #{record.type,jdbcType=INTEGER}");
        sql.SET("atk = #{record.atk,jdbcType=INTEGER}");
        sql.SET("def = #{record.def,jdbcType=INTEGER}");
        sql.SET("level = #{record.level,jdbcType=INTEGER}");
        sql.SET("race = #{record.race,jdbcType=INTEGER}");
        sql.SET("attribute = #{record.attribute,jdbcType=INTEGER}");
        sql.SET("category = #{record.category,jdbcType=INTEGER}");
        sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        sql.SET("description = #{record.description,jdbcType=VARCHAR}");
        sql.SET("sum = #{record.sum,jdbcType=INTEGER}");
        
        DatasExample example = (DatasExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    public String updateByPrimaryKeySelective(Datas record) {
        SQL sql = new SQL();
        sql.UPDATE("datas");
        
        if (record.getOt() != null) {
            sql.SET("ot = #{ot,jdbcType=INTEGER}");
        }
        
        if (record.getAlias() != null) {
            sql.SET("alias = #{alias,jdbcType=INTEGER}");
        }
        
        if (record.getSetcode() != null) {
            sql.SET("setcode = #{setcode,jdbcType=INTEGER}");
        }
        
        if (record.getType() != null) {
            sql.SET("type = #{type,jdbcType=INTEGER}");
        }
        
        if (record.getAtk() != null) {
            sql.SET("atk = #{atk,jdbcType=INTEGER}");
        }
        
        if (record.getDef() != null) {
            sql.SET("def = #{def,jdbcType=INTEGER}");
        }
        
        if (record.getLevel() != null) {
            sql.SET("level = #{level,jdbcType=INTEGER}");
        }
        
        if (record.getRace() != null) {
            sql.SET("race = #{race,jdbcType=INTEGER}");
        }
        
        if (record.getAttribute() != null) {
            sql.SET("attribute = #{attribute,jdbcType=INTEGER}");
        }
        
        if (record.getCategory() != null) {
            sql.SET("category = #{category,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("description = #{description,jdbcType=VARCHAR}");
        }
        
        if (record.getSum() != null) {
            sql.SET("sum = #{sum,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datas
     *
     * @mbg.generated Sun Nov 29 12:57:16 JST 2020
     */
    protected void applyWhere(SQL sql, DatasExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}